### ISSUE TITLE
Kubernetes 

### ISSUE THREAD

**Issue by mitkox** [hivemq/hivemq-edge#23]
## Problem or use case
Can you put the helm charts or deployment yaml files for running hivemq-edge on Kubernetes? Kubernetes for edge computing is becoming the standard.

**Comment by simon622** [comment]
Hey Dimitar - we are aware and this is indeed coming shortly, thank you for the input.

**Comment by mitkox** [comment]
apiVersion: apps/v1
kind: Deployment
metadata:
 name: hivemq-deployment
spec:
 replicas: 1
 selector:
  matchLabels:
   app: hivemq
 template:
  metadata:
   labels:
    app: hivemq
  spec:
   containers:
   - name: hivemq
    image: mitko
    ports:
    - containerPort: 1883
    - containerPort: 2442
    - containerPort: 8080
    volumeMounts:
    - name: log-volume
     mountPath: /opt/hivemq/log
   volumes:
   - name: log-volume
    emptyDir: {}

**Comment by JMayrbaeurl** [comment]
That's the one I've recently used on AKS EE for the version 2023.3:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hivemqedge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hivemq-edge
  template:
    metadata:
      labels:
        app: hivemq-edge
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: hivemq-edge
          image: hivemq/hivemq-edge:2023.3
          ports:
           - containerPort: 1883
           - containerPort: 8080
          volumeMounts:
           - name: hivemq-edge-log-volume
             mountPath: /opt/hivemq/log
      volumes:
        - name: hivemq-edge-log-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: hivemq-edge
spec:
  type: LoadBalancer
  ports:
    - port: 1883
      name: hme-mqtt
    - port: 8080
      name: hme-ui
  selector:
    app: hivemq-edge
```
